crm/templatetags/urls.py
from django.shortcuts import reverse
from django import template

register = template.Library()


@register.simple_tag
def reverse_url(request, name, *args ,**kwargs):
    base_url = reverse(name, args=args, kwargs=kwargs)
    params = request.GET.urlencode()

    if not params:
        return base_url
    return '{}?{}'.format(base_url, params)

crm/urls.py
from django.urls import path,re_path
from crm import views
urlpatterns = [
    # path('customer/', views.customer, name="customer"),
    path('page/', views.page),
    path('page2/', views.page2),
    # path('customer_add/', views.customer_add, name="customer_add"),
    path('customer_add/', views.customer_change, name="customer_add"),
    # re_path('^customer_edit/(\d+)/', views.customer_edit, name="customer_edit"),
    re_path('^customer_edit/(\d+)/', views.customer_change, name="customer_edit"),
    # path('my_customer/', views.customer, name="my_customer"),
    path('customer/', views.Customer.as_view(), name="customer"),
    path('my_customer/', views.Customer.as_view(), name="my_customer"),

    # 跟进记录相关
    re_path('consult/(?P<customer_id>\d+)', views.Consult.as_view(), name="consult"),
    path('consult_add', views.consult_add, name="consult_add"),
    re_path('consult_edit/(?P<edit_id>\d+)', views.consult_edit, name="consult_edit"),

    # 报名记录相关
    re_path('^enrollment/(?P<customer_id>\d+)', views.Enroll.as_view(), name="enrollment"),
    re_path('^enrollment_add/(?P<customer_id>\d+)', views.enrollment_add, name="enrollment_add"),
]

crm/utils/urls.py
from django.shortcuts import reverse


def reverse_url(request, name, *args, **kwargs):
    base_url = reverse(name, args=args, kwargs=kwargs)
    params = request.GET.urlencode()
    if not params:
        return base_url
    return'{}?{}'.format(base_url, params)

crm用户管理系统/urls.py
from django.contrib import admin
from django.urls import path,include
from crm import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login,name="login"),
    path('logout/', views.logout,name="logout"),
    path('index/', views.index, name="index"),
    path('reg/', views.reg,name="reg"),
    path('crm/', include('crm.urls')),
]

crm/models.py
from django.db import models
from multiselectfield import MultiSelectField
from django.utils.safestring import mark_safe


course_choices = (('Linux', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'),)
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class Department(models.Model):
    """
    部门表
    """
    name = models.CharField(max_length=32, verbose_name="部门名称")
    count = models.IntegerField(verbose_name="人数", default=0)

    # class Meta:
    #     db_table = 'xxx'   # 表名
    def __str__(self):
        return self.name


class UserProfile(models.Model):
    """
    用户表
    """
    username = models.EmailField(max_length=255, unique=True,verbose_name="用户名")
    password = models.CharField(max_length=128, verbose_name="密码")
    name = models.CharField(max_length=32, verbose_name="真实姓名")
    department = models.ForeignKey('Department', default=None, blank=True, null=True,verbose_name="所属部门", on_delete=models.CASCADE)
    mobile = models.CharField(verbose_name='手机号', max_length=32, default=None, blank=True, null=True,)
    memo = models.TextField(verbose_name='备注', blank=True, null=True, default=None)
    date_joined = models.DateTimeField(auto_now_add=True,verbose_name="入职时间")
    is_active = models.BooleanField(default=True,verbose_name="活跃度")

    def __str__(self):
        return self.name


class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField('QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, blank=True, null=True, help_text='学员报名后，请改为真实姓名')
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True, null=True)
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.BigIntegerField('手机号', blank=True, null=True)
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True, on_delete=models.CASCADE)
    course = MultiSelectField("咨询课程", choices=course_choices)
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")
    network_consult_note = models.TextField(blank=True, null=True, verbose_name='网络咨询师咨询内容')
    date = models.DateTimeField("咨询日期", auto_now_add=True)
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)
    network_consultant = models.ForeignKey('UserProfile', blank=True, null=True, verbose_name='咨询师',
                                           related_name='network_consultant',on_delete=models.CASCADE)
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", related_name='customers', blank=True, null=True, on_delete=models.CASCADE)
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", blank=True)

    def show_classes(self):
        return " |".join(str(i) for i in self.class_list.all())   # 列表生成式 存放一个个对象的字符串

    def show_state(self):
        color_dict={
            'signed': "red",
             'unregistered': "yellow",
             'studying': 'blue',
             'paid_in_full': "green"
            }
        return mark_safe('<span style="background-color:{};color:white; padding:3px;">{}</span>'.format(color_dict.get(self.status), self.get_status_display()))

    def __str__(self):
        return "{}+{}".format(self.qq, self.name)


class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campuses', verbose_name="校区",on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=10000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)
    teachers = models.ManyToManyField('UserProfile', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班额及类型', blank=True,
                                  null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return "{}{}({})".format(self.get_course_display(), self.semester, self.campuses)


class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户", on_delete=models.CASCADE)
    note = models.TextField(verbose_name="跟进内容...")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserProfile", verbose_name="跟进人", related_name='records',on_delete=models.CASCADE)
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)


class Enrollment(models.Model):
    """
    报名表
    """

    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    contract_agreed = models.BooleanField("我已认真阅读完培训协议并同意全部协议内容", default=False)
    contract_approved = models.BooleanField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", default=False)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称', on_delete=models.CASCADE)
    school = models.ForeignKey('Campuses', on_delete=models.CASCADE, verbose_name="校区")
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级", on_delete=models.CASCADE)

    class Meta:
        unique_together = ('enrolment_class', 'customer')


class PaymentRecord(models.Model):
    """
    缴费记录表
    """
    pay_type = models.CharField("费用类型", choices=pay_type_choices, max_length=64, default="deposit")
    paid_fee = models.IntegerField("费用数额", default=0)
    note = models.TextField("备注", blank=True, null=True)
    date = models.DateTimeField("交款日期", auto_now_add=True)
    course = models.CharField("课程名", choices=course_choices, max_length=64, blank=True, null=True, default='N/A')
    class_type = models.CharField("班级类型", choices=class_type_choices, max_length=64, blank=True, null=True,
                                  default='N/A')
    enrolment_class = models.ForeignKey('ClassList', verbose_name='所报班级', blank=True, null=True,on_delete=models.CASCADE)
    customer = models.ForeignKey('Customer', verbose_name="客户",on_delete=models.CASCADE)
    consultant = models.ForeignKey('UserProfile', verbose_name="销售", on_delete=models.CASCADE)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)

    status_choices = (
        (1, '未审核'),
        (2, '已审核'),
    )
    status = models.IntegerField(verbose_name='审核', default=1, choices=status_choices)

    confirm_date = models.DateTimeField(verbose_name="确认日期", null=True, blank=True)
    confirm_user = models.ForeignKey(verbose_name="确认人", to='UserProfile', related_name='confirms', null=True,
                                     blank=True,on_delete=models.CASCADE)


class CourseRecord(models.Model):
    """课程记录表"""
    day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
    date = models.DateField(auto_now_add=True, verbose_name="上课日期")
    course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")

crm/forms.py
from django import forms
from crm import models
from django.core.exceptions import ValidationError
import hashlib


class BootStrapForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})


class RegForm(BootStrapForm):
    password = forms.CharField(min_length=6, label="密码", widget=forms.PasswordInput)
    re_password = forms.CharField(min_length=6, label="确认密码", widget=forms.PasswordInput)

    class Meta:
        model = models.UserProfile     # 数据库
        fields = '__all__'   # 要显示的字段
        exclude = ["is_active"]  # 不显示的字段
        labels = {
            # 需要显示的中文名
            # "password": "密码"
        }
        widgets = { # HTML插件
            # 'password': forms.PasswordInput(attrs={'class': 'form-control'})
        }
        error_messages = {
            'username': {
                "required": "不能为空",
                "invalid": "格式错误"
            }
        }

    def clean(self):
        pwd = self.cleaned_data.get("password")
        re_pwd = self.cleaned_data.get("re_password")

        if pwd != re_pwd:
            self.add_error('re_password', "两次密码不一致")
            raise ValidationError("两次密码不一致")
        md5 = hashlib.md5()
        md5.update(pwd.encode("utf8"))
        pwd = md5.hexdigest()
        self.cleaned_data["password"] = pwd
        return self.cleaned_data


class UserForm(BootStrapForm):

    class Meta:
        model = models.Customer
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['course'].widget.attrs = {}


class ConsultForm(BootStrapForm):

    class Meta:
        model = models.ConsultRecord
        fields = "__all__"

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

        self.fields["customer"].choices = [(i.pk, str(i)) for i in self.instance.consultant.customers.all()]
        self.fields["consultant"].choices = [(self.instance.consultant.pk,self.instance.consultant.name)]


class EnrollmentForm(BootStrapForm):

    class Meta:
        model = models.Enrollment
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.customer_id != '0':
            self.fields["customer"].choices=[(self.instance.customer_id,str(self.instance.customer))]
            self.fields["enrolment_class"].choices = [(i.pk, str(i)) for i in self.instance.customer.class_list.all()]

crm/templates/consult.html
{% extends "layout.html" %}

{% block content %}
    <a href="{% url 'consult_add' %}" class="btn btn-danger">添加跟进记录</a>
    <table style="margin: 15px" class="table-hover table table-bordered">
        <thead>
        <tr>
            <td>序号</td>
            <td>跟进记录</td>
            <td>跟进状态</td>
            <td>跟进日期</td>
            <td>客户</td>
            <td>跟进人</td>
            <td>删除状态</td>
            <td>操作</td>
        </tr>
        </thead>
        <tbody>
        {% for foo in consult_obj %}
            <tr>
            <td>{{ forloop.counter}}</td>
            <td>{{ foo.note }}</td>
            <td>{{ foo.get_status_display }}</td>
            <td>{{ foo.date }}</td>
            <td>{{ foo.customer }}</td>
            <td>{{ foo.consultant }}</td>
            <td>{{ foo.delete_status }}</td>
            <td><a href="{% url "consult_edit" foo.pk %}"><i class="fa fa-pencil-square-o">编辑</i></a></td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}

crm/templates/consult_add.html
{% extends "layout.html" %}

{% block content %}
<div class="panel panel-default" style="margin: 15px">
  <div class="panel-heading">
    <h3 class="panel-title">添加用户</h3>
  </div>
  <div class="panel-body">
      <form action="" method="post" novalidate>
      {% csrf_token %}
          {% for consult in consult_obj%}
              <div class="form-group">
                  <label for="{{ consult.id_for_label }}">{{ consult.label }}</label>
                  {{ consult }}
                  <span>{{ consult.errors.0 }}</span>
              </div>
          {% endfor %}
      <button>提交</button>
      </form>
  </div>
</div>
{% endblock %}

crm/templates/consult_edit.html
{% extends "layout.html" %}

{% block content %}
<div class="panel panel-default" style="margin: 15px">
  <div class="panel-heading">
    <h3 class="panel-title">编辑用户</h3>
  </div>
  <div class="panel-body">
      <form action="" method="post" novalidate>
      {% csrf_token %}
          {% for consult in consult_obj%}
              <div class="form-group">
                  <label for="{{ consult.id_for_label }}">{{ consult.label }}</label>
                  {{ consult }}
                  <span>{{ consult.errors.0 }}</span>
              </div>
          {% endfor %}
      <button>提交</button>
      </form>
  </div>
</div>
{% endblock %}

crm/templates/customer.html
{% extends "layout.html" %}
{% block content %}
    {% load urls %}
    <audio src="/static/audio/化身孤岛的鲸.mp3" autoplay="autoplay" loop="loop"></audio>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <a href="{% url "customer_add" %}" class="btn btn-success">添加客户</a>
                <br>
                <br>
                <form action="" class="form-inline pull-right">
                    <input type="text" class="form-control" name="query">
                    <button class="btn btn-primary btn-sm">提交</button>
                </form>
                <form action="" method="post" class="form-inline">
                    {% csrf_token %}
                    <select name="action" id="" class="form-control">
                        <option value="">选择操作方式</option>
                        <option value="public">私户转公户</option>
                        <option value="private">公户转私户</option>
                        <option value="public_delete">批量删除</option>
                    </select>
                    <button class="btn btn-sm btn-primary">确定</button>
                    <table class="table table-striped table-hover table-bordered">
                        <thead>
                        <tr>
                            <th>选择</th>
                            <th>序号</th>
                            <th>QQ号</th>
                            <th>姓名</th>
                            <th>性别</th>
                            <th>生日</th>
                            <th>客户来源</th>
                            <th>咨询课程</th>
                            <th>状态</th>
                            <th>咨询日期</th>
                            <th>销售</th>
                            <th>已报班级</th>
                            <th>跟进记录</th>
                            <th>报名记录</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for customer in all_customer %}
                            <tr>
                                <td><input type="checkbox" name="id" value="{{ customer.pk }}"></td>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ customer.qq }}</td>
                                <td>{{ customer.name|default:"" }}</td>
                                <td>{{ customer.get_sex_display }}</td>
                                <td>{{ customer.birthday|date:"Y-m-d" }}</td>
                                <td>{{ customer.get_source_display }}</td>
                                <td>{{ customer.get_course_display }}</td>
                                <td>{{ customer.show_state }}</td>
                                <td>{{ customer.date }}</td>
                                {# seetting里面设置USE_L10N =False DATETIME_FORMAT='Y-m-d H:i:s'  #}
                                <td>{{ customer.consultant|default:"未添加" }}</td>
                                <td>{{ customer.show_classes }}</td>
                                <td><a href="{% url 'consult' customer.pk %}">查看记录</a></td>
                                <td><a href="{% url 'enrollment_add' customer.pk %}">添加信息</a></td>
                                <td><a href="{% reverse_url request "customer_edit" customer.pk %}"><i
                                        class="fa fa-pencil-square-o"></i>编辑</a></td>
                            </tr>

                        {% endfor %}

                        </tbody>
                    </table>
                </form>

                <nav aria-label="Page navigation" style="text-align: center">
                    <ul class="pagination">
                        {{ page_html|safe }}
                    </ul>
                </nav>
            </div>
        </div>
    </div>

{% endblock %}

crm/templates/customer_add.html
{% extends "layout.html" %}

{% block content %}
<div class="panel panel-default" style="margin: 15px">
  <div class="panel-heading">
    <h3 class="panel-title">添加用户</h3>
  </div>
  <div class="panel-body">
      <form action="" method="post" novalidate>
      {% csrf_token %}
          {% for user in user_obj %}
              <div class="form-group">
                  <label for="{{ user.id_for_label }}">{{ user.label }}</label>
                  {{ user }}
                  <span>{{ user.errors.0 }}</span>
              </div>
          {% endfor %}
      <button>提交</button>
      </form>
  </div>
</div>
{% endblock %}

crm/templates/customer_change.html
{% extends "layout.html" %}

{% block content %}
    <form action="" method="post" novalidate>
    {% csrf_token %}
        {% for user in user_obj %}
            <div class="form-group">
                <label for="{{ user.id_for_label }}">{{ user.label }}</label>
                {{ user }}
                <span>{{ user.errors.0 }}</span>
            </div>
        {% endfor %}
        <button>提交</button>
    </form>
{% endblock %}

crm/templates/customer_edit.html
{% extends "layout.html" %}

{% block content %}
    <form action="" method="post" novalidate>
    {% csrf_token %}
    {% for field in user_obj %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
        <span>{{ field.errors.0 }}</span>
        </div>
    {% endfor %}
    <button>提交</button>
    </form>
{% endblock %}

crm/templates/enrollment.html
{% extends "layout.html" %}

{% block content %}
    <a href="{% url 'enrollment_add' '0' %}" class="btn btn-primary btn-sm">添加</a>
    <table style="margin: 15px" class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>序号</th>
        <th>名字</th>
        <th>报名原因</th>
        <th>期待值</th>
        <th>是否同意协议</th>
        <th>申请是否通过</th>
        <th>报名日期</th>
        <th>校区</th>
        <th>班级</th>
    </tr>
    </thead>
    <tbody>
    {% for foo in  enrollment_obj %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ foo.customer }}</td>
        <td>{{ foo.why_us }}</td>
        <td>{{ foo.your_expectation }}</td>
        <td>{{ foo.contract_agreed }}</td>
        <td>{{ foo.contract_approved }}</td>
        <td>{{ foo.enrolled_date }}</td>
        <td>{{ foo.school }}</td>
        <td>{{ foo.enrolment_class }}</td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
{% endblock %}

crm/templates/enrollment_change.html
{% extends "layout.html" %}

{% block content %}
    <form action="" method="post" novalidate>
    {% for foo in enrollment_obj %}
        {% csrf_token %}
        <label for="{{ foo.id_for_label }}">{{ foo.label }}</label>
        {{ foo }}
        <span>{{ foo.errors.0 }}</span>
    {% endfor %}
    <button>提交</button>
    </form>
{% endblock %}

crm/templates/page.html
{% extends 'layout.html' %}
{% block content %}
    <h3>分页界面</h3>
    <table class="table-bordered table table-hover">
        <thead>
        <tr>
            <th>序号</th>
            <th>名字</th>
            <th>密码</th>
        </tr>
        </thead>
        <tbody>
        {% for user in user_list %}
            <tr>
                <th>{{ forloop.counter }}</th>
                <th>{{ user.name }}</th>
                <th>{{ user.pwd }}</th>
            </tr>
        {% endfor %}


        </tbody>
    </table>
    <nav aria-label="Page navigation" style="text-align: center">
        <ul class="pagination">

            {% if page_after < 1 %}
                <li class="disabled"><a href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a></li>

            {% else %}
                <li><a href="?page={{ page_after }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a></li>

            {% endif %}

            {% for page in page_num %}
                {% if now_page == page %}
                    <li class="active"><a href="?page={{ page }}">{{ page }}</a></li>
                {% else %}
                    <li><a href="?page={{ page }}">{{ page }}</a></li>
                {% endif %}
            {% endfor %}
        {% if page_before == paged %}
            <li class="disabled">
                <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% else %}
            <li>
                <a href="?page={{ page_before }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}

        </ul>
    </nav>
{% endblock %}

crm/templates/page2.html
{% extends 'layout.html' %}
{% block content %}
    <h3>分页界面</h3>
    <table class="table-bordered table table-hover">
        <thead>
        <tr>
            <th>序号</th>
            <th>名字</th>
            <th>密码</th>
        </tr>
        </thead>
        <tbody>
        {% for user in all_user %}
            <tr>
                <th>{{ forloop.counter }}</th>
                <th>{{ user.name }}</th>
                <th>{{ user.pwd }}</th>
            </tr>
        {% endfor %}


        </tbody>
    </table>
    <nav aria-label="Page navigation" style="text-align: center">
        <ul class="pagination">
            {{ page_html|safe }}
        </ul>
    </nav>
{% endblock %}